name: Build Kernel
on:
  workflow_dispatch:
    inputs:
      BRANCH:
        description: Kernel branch
        default: 'master'
        required: true
      KSU:
        description: Add KernelSU support
        type: boolean
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get date
      id: rundate
      run: sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/Asia/Jakarta /etc/localtime && echo "REPO_DATE=`date`" >> $GITHUB_OUTPUT
    
    - uses: actions/checkout@v4
      with:
        path: kernel_root
        repository: repotitan/android_kernel_asus_sdm660-4.19
        ref: ${{ github.event.inputs.BRANCH }}
        show-progress: false
        fetch-depth: 1

    - name: Prepare dependencies
      run: |
        sudo apt update -y
        sudo apt install bc cpio flex bison aptitude git python-is-python3 tar perl wget curl lz4 -y
        sudo aptitude install libssl-dev -y

    - name: Build kernel
      id: buildKernel
      run: |
        if [[ "${{ github.event.inputs.KSU }}" = "true" ]]; then
          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
        fi
        export IS_CI=true
        bash build-X01BD.sh
        if [ -e $(pwd)/out/.config ]; then
          mv out/.config out/defconfig
        fi
        # Reduce the size
        rm out/arch/arm64/boot/Image
      working-directory: kernel_root

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build-RSU_X01BDA
        path: kernel_root/out/arch/arm64/boot/*
        compression-level: 9

    - name: Upload configs
      uses: actions/upload-artifact@v4
      with:
        name: Defconfig-RSU_X01BDA
        path: kernel_root/out/defconfig

    - name: Upload AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3-RSU_X01BDA
        path: kernel_root/AnyKernel3/*
        compression-level: 9

    - name: Cleanup useless files
      continue-on-error: true
      run: |
        rm out/vmlinux.o out/vmlinux out/System.map
      working-directory: kernel_root
